import mongoose from "mongoose";

const userIds = [
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
  new mongoose.Types.ObjectId(),
];

export const users = [
  {
    _id: userIds[0],
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p11.jpeg",
    friends: [],
    location: "New York, NY",
    description: "I may be a software engineer, but my real passion is staring at a blank screen. Also, I'm secretly a robot.",
    occupation: "Software Engineer",
    profileViews: 7500,
    profileLikes: 6500,
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: userIds[1],
    firstName: "Jane",
    lastName: "Smith",
    email: "janesmith@example.com",
    password: "$!FEAS@!O)_IDJda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p3.jpeg",
    friends: [],
    location: "Los Angeles, CA",
    description: "I'm a graphic designer who specializes in making things look pretty, if you can't tell from my Instagram",
    occupation: "Graphic Designer",
    profileViews: 9000,
    profileLikes: 7500,
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: userIds[2],
    firstName: "Bob",
    lastName: "Johnson",
    email: "bobjohnson@example.com",
    password: "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    picturePath: "p4.jpeg",
    friends: [],
    location: "Chicago, IL",
    description: "Product manager by day, professional coffee drinker by night",
    occupation: "Product Manager",
    profileViews: 8500,
    profileLikes: 7500,
    createdAt: 1288090662,
    updatedAt: 1288090662,
    __v: 0,
  },
  {
    _id: userIds[3],
    firstName: "Charlie",
    lastName: "Williams",
    email: "charliewilliams@example.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p6.jpeg",
    friends: [],
    location: "Houston, TX",
    description: "Data scientist extraordinaire. I can predict the future but I'm terrible at making decisions",
    occupation: "Data Scientist",
    profileViews: 9000,
    profileLikes: 7800,
    createdAt: 1219214568,
    updatedAt: 1219214568,
    __v: 0,
  },
  {
    _id: userIds[4],
    firstName: "Emily",
    lastName: "Jones",
    email: "emilyjones@example.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p5.jpeg",
    friends: [],
    location: "Philadelphia, PA",
    description: "I make boring subjects interesting, it's a super power, trust me.",
    occupation: "Content Writer",
    profileViews: 9200,
    profileLikes: 8500,
    createdAt: 1493463661,
    updatedAt: 1493463661,
    __v: 0,
  },
  {
    _id: userIds[5],
    firstName: "Michael",
    lastName: "Brown",
    email: "michaelbrown@example.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p7.jpeg",
    friends: [],
    location: "Phoenix, AZ",
    description: "I build websites, but I'm also known to build pretty decent sandcastles.",
    occupation: "Full-Stack Developer",
    profileViews: 8700,
    profileLikes: 7500,
    createdAt: 1381326073,
    updatedAt: 1381326073,
    __v: 0,
  },
  {
    _id: userIds[6],
    firstName: "Sarah",
    lastName: "Miller",
    email: "sarahmiller@example.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p8.jpeg",
    friends: [],
    location: "San Diego, CA",
    description: "Social media specialist, master of the #ThrowbackThursday",
    occupation: "Social Media Specialist",
    profileViews: 9000,
    profileLikes: 8500,
    createdAt: 1714704324,
    updatedAt: 1642716557,
    __v: 0,
  },
  {
    _id: userIds[7],
    firstName: "David",
    lastName: "Moore",
    email: "davidmoore@example.com",
    password: "$2b$10$dsasdgsagasda//G9JxQ4bQ8KXf4OAIe/X/AK9skyWUy",
    picturePath: "p9.jpeg",
    friends: [],
    location: "Tampa, FL",
    description: "I'm a business analyst, which means I have a lot of opinions and excel spreadsheets",
    occupation: "Business Analyst",
    profileViews: 7500,
    profileLikes: 4000,
    createdAt: 1369908044,
    updatedAt: 1359322268,
    __v: 0,
  },
];

export const posts = [
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[1],
    firstName: "Jane",
    lastName: "Smith",
    description: "",
    location: "The Leaning Tower of Pisa, Italy",
    description: "Just visited the Leaning Tower of Pisa and it was incredible! The lean is definitely noticeable but it's such an iconic landmark #Pisa #LeaningTower",
    picturePath: "post1.jpg",
    userPicturePath: "p3.jpeg",
    likes: new Map([
      [userIds[0], true],
      [userIds[2], true],
      [userIds[3], true],
      [userIds[4], true],
    ]),
    comments: [
        "Wow, looks amazing! Can't wait to visit",
        "I love how you captured the lean in your photo! Looks like it's about to fall over",
        "Been wanting to visit for so long, thanks for the inspiration!",
        "I need to go back, it's been years since my last visit! How was the climb?"
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[3],
    firstName: "Charlie",
    lastName: "Williams",
    description: "",
    location: "Mount Rushmore, USA",
    description: "Had the pleasure of visiting Mount Rushmore today! So much history and patriotism in one place. #MountRushmore #Presidential",
    picturePath: "post2.jpg",
    userPicturePath: "p6.jpeg",
    likes: new Map([
      [userIds[7], true],
      [userIds[4], true],
      [userIds[1], true],
      [userIds[2], true],
    ]),
    comments: [
        "Looks like a fantastic place to visit. How was the weather?",
        "So jealous, I've always wanted to go there",
        "Such an iconic American landmark, love it",
        "Thanks for sharing your experience, it makes me want to go even more!"
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[4],
    firstName: "Emily",
    lastName: "Jones",
    description: "",
    location: "The Sphinx, Egypt",
    description: "The Sphinx was even more impressive in person! It's truly mesmerizing to stand before such an ancient and mysterious monument. #Sphinx #AncientEgypt",
    picturePath: "post3.jpg",
    userPicturePath: "p5.jpeg",
    likes: new Map([
      [userIds[1], true],
      [userIds[6], true],
      [userIds[3], true],
      [userIds[5], true],
    ]),
    comments: [
        "Looks like an amazing experience, thanks for sharing",
        "I've never seen a more majestic creature in my life",
        "I can only imagine how awe-inspiring it must be to stand before it",
        "So much history and mystery in one statue, how long did you spend there?"
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[5],
    firstName: "Michael",
    lastName: "Brown",
    description: "",
    location: "Cancun, Mexico",
    description: "Cancun is the perfect place to relax and forget about the world, especially if you're a fan of sandy beaches and clear blue waters. #Cancun #Beach",
    picturePath: "post4.jpg",
    userPicturePath: "p7.jpeg",
    likes: new Map([
      [userIds[1], true],
      [userIds[6], true],
      [userIds[3], true],
    ]),
    comments: [
        "I heard the drinks are extra strong in Cancun, did you confirm?",
        "I heard that the beaches there are so beautiful, they make you forget all your problems, did you confirm?",
        "I heard that the water is so clear you can see through to the other side, did you confirm?",
        "I heard that the sand is so soft you can bury yourself in it"
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[6],
    firstName: "Sarah",
    lastName: "Miller",
    description: "",
    location: "The Statue of Liberty, New York, USA",
    description: "Just visited the Statue of Liberty and it was lit-er-ally a towering experience! #StatueofLiberty #NewYork",
    picturePath: "post5.jpg",
    userPicturePath: "p8.jpeg",
    likes: new Map([
      [userIds[1], true],
      [userIds[3], true],
      [userIds[5], true],
      [userIds[7], true],
    ]),
    comments: [
        "Did you make a wish at the top?",
        "I heard you can see the whole city from up there, is that true?",
        "Is the view from the crown as breathtaking as they say?",
        "I heard the statue is made of copper, did you turn green while you were there?"
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    userId: userIds[7],
    firstName: "David",
    lastName: "Moore",
    description: "",
    location: "The Great Wall of China, China",
    description: "Just finished walking the Great Wall of China! My feet hurt, but the views were worth it! #GreatWallofChina #China",
    picturePath: "post6.jpg",
    userPicturePath: "p9.jpeg",
    likes: new Map([
      [userIds[1], true],
      [userIds[2], true],
    ]),
    comments: [
        "I heard it's so long, you can see it from space, is that true?",
        "Did you find any good spots to take a break?",
        "I heard the wall is over 2,000 years old, did you run into any ghosts?",
        "I heard it's one of the Seven Wonders of the World, is that true? Because I only count six in my head"
    ],
  },
];